/** Shared immutable request-header policy for mediated egress paths. */

import { HOP_BY_HOP_HEADERS } from './hop-by-hop-headers.js';

/** Credentials an untrusted workload must never relay through an egress proxy. */
export const EGRESS_FORBIDDEN_CREDENTIAL_HEADERS: ReadonlySet<string> = new Set([
  'authorization',
  'proxy-authorization',
  'cookie',
  'set-cookie',
  'x-api-key',
  'x-goog-api-key',
  'anthropic-api-key',
]);

/** Headers regenerated by the destination-bound transport rather than relayed. */
export const EGRESS_DROPPED_REQUEST_HEADERS: ReadonlySet<string> = new Set(['host', ...HOP_BY_HOP_HEADERS]);
