/**
 * Proxy MCP Server tool definitions, annotations, and policy rules.
 *
 * These are hardcoded (not generated by the LLM pipeline) because the
 * proxy tools have known, fixed semantics. The annotations and rules
 * are injected into the PolicyEngine at startup so that domain
 * management calls go through normal policy evaluation and audit logging.
 */

import * as http from 'node:http';
import type { CompiledRule, StoredToolAnnotation } from '../pipeline/types.js';

// ---------------------------------------------------------------------------
// Domain validation
// ---------------------------------------------------------------------------

const DOMAIN_RE = /^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$/i;
const IP_RE = /^\d{1,3}(\.\d{1,3}){3}$/;
const DOCKER_INTERNAL_SUFFIX = '.docker.internal';

/** Validates a domain string for use as a passthrough host. */
export function validateDomain(domain: string): void {
  if (domain.length > 253) throw new Error(`Domain too long (${domain.length} > 253)`);
  if (domain.toLowerCase() === 'localhost') {
    throw new Error(`Blocked host: "${domain}"`);
  }
  if (!DOMAIN_RE.test(domain)) throw new Error(`Invalid domain format: "${domain}"`);
  if (IP_RE.test(domain)) throw new Error(`IP addresses are not allowed: "${domain}"`);
  if (domain.toLowerCase().endsWith(DOCKER_INTERNAL_SUFFIX)) {
    throw new Error(`Blocked host: "${domain}" (*.docker.internal is not allowed)`);
  }
}

// ---------------------------------------------------------------------------
// Domain listing type
// ---------------------------------------------------------------------------

export interface DomainListing {
  /** Statically configured LLM provider hosts (with key swap). */
  readonly providers: readonly string[];
  /** Dynamically added passthrough hosts (no key swap). */
  readonly dynamic: readonly string[];
}

// ---------------------------------------------------------------------------
// MCP tool schemas
// ---------------------------------------------------------------------------

/** MCP tool definitions for the proxy server. */
export const proxyToolDefinitions = [
  {
    name: 'add_proxy_domain',
    description:
      'Request access to an additional internet domain through the network proxy. ' +
      'This will be reviewed by a human before being granted. ' +
      'Provide a clear justification for why the domain is needed.',
    inputSchema: {
      type: 'object' as const,
      properties: {
        domain: {
          type: 'string',
          description: 'The exact domain name to allow (e.g., "api.example.com"). No wildcards.',
        },
        justification: {
          type: 'string',
          description:
            'Explanation of why this domain is needed for the current task. ' +
            'This text is shown to the human reviewer.',
        },
      },
      required: ['domain', 'justification'],
    },
  },
  {
    name: 'remove_proxy_domain',
    description:
      'Remove a previously approved domain from the proxy allowlist. ' +
      'Only dynamically added domains can be removed; built-in provider domains cannot.',
    inputSchema: {
      type: 'object' as const,
      properties: {
        domain: {
          type: 'string',
          description: 'The domain name to remove.',
        },
      },
      required: ['domain'],
    },
  },
  {
    name: 'list_proxy_domains',
    description:
      'List all domains currently accessible through the network proxy. ' +
      'Includes both built-in provider domains and dynamically added domains.',
    inputSchema: {
      type: 'object' as const,
      properties: {},
    },
  },
] as const;

// ---------------------------------------------------------------------------
// Tool annotations (hardcoded, not LLM-generated)
// ---------------------------------------------------------------------------

const schemaByName = Object.fromEntries(
  proxyToolDefinitions.map((t) => [t.name, t.inputSchema as Record<string, unknown>]),
) as Record<(typeof proxyToolDefinitions)[number]['name'], Record<string, unknown>>;

export const proxyAnnotations: StoredToolAnnotation[] = [
  {
    toolName: 'add_proxy_domain',
    serverName: 'proxy',
    comment: 'Add a domain to the MITM proxy allowlist',
    args: {
      domain: ['proxy-domain'],
      justification: ['none'],
    },
    inputSchema: schemaByName.add_proxy_domain,
  },
  {
    toolName: 'remove_proxy_domain',
    serverName: 'proxy',
    comment: 'Remove a domain from the MITM proxy allowlist',
    args: {
      domain: ['proxy-domain'],
    },
    inputSchema: schemaByName.remove_proxy_domain,
  },
  {
    toolName: 'list_proxy_domains',
    serverName: 'proxy',
    comment: 'List currently allowed proxy domains',
    args: {},
    inputSchema: schemaByName.list_proxy_domains,
  },
];

// ---------------------------------------------------------------------------
// Compiled policy rules (hardcoded)
// ---------------------------------------------------------------------------

export const proxyPolicyRules: CompiledRule[] = [
  {
    name: 'proxy-add-domain-escalate',
    description: 'Adding network domains requires human review',
    principle: 'Human oversight',
    if: { server: ['proxy'], tool: ['add_proxy_domain'] },
    then: 'escalate',
    reason: 'Adding network domains expands the container attack surface and requires human review',
  },
  {
    name: 'proxy-remove-domain-allow',
    description: 'Removing domains reduces attack surface',
    principle: 'Least privilege',
    if: { server: ['proxy'], tool: ['remove_proxy_domain'] },
    then: 'allow',
    reason: 'Removing domains reduces the attack surface',
  },
  {
    name: 'proxy-list-domains-allow',
    description: 'Listing domains is a read-only operation',
    principle: 'Least privilege',
    if: { server: ['proxy'], tool: ['list_proxy_domains'] },
    then: 'allow',
    reason: 'Read-only operation with no side effects',
  },
];

// ---------------------------------------------------------------------------
// Control API client
// ---------------------------------------------------------------------------

export interface ControlApiClient {
  addDomain(domain: string): Promise<{ added: boolean }>;
  removeDomain(domain: string): Promise<{ removed: boolean }>;
  listDomains(): Promise<DomainListing>;
}

/**
 * Creates an HTTP client for the MITM proxy's domain control API.
 *
 * @param controlAddr - "unix:///path/to/socket" or "http://127.0.0.1:PORT"
 */
export function createControlApiClient(controlAddr: string): ControlApiClient {
  const isUnix = controlAddr.startsWith('unix://');
  const socketPath = isUnix ? controlAddr.slice('unix://'.length) : undefined;
  const baseUrl = isUnix ? 'http://localhost' : controlAddr;

  function request(method: string, path: string, body?: unknown): Promise<unknown> {
    return new Promise((resolve, reject) => {
      const url = new URL(path, baseUrl);
      const opts: http.RequestOptions = {
        method,
        hostname: url.hostname,
        port: url.port || undefined,
        path: url.pathname,
        headers: { 'Content-Type': 'application/json' },
        ...(socketPath ? { socketPath } : {}),
      };

      const req = http.request(opts, (res) => {
        const chunks: Buffer[] = [];
        res.on('data', (chunk: Buffer) => chunks.push(chunk));
        res.on('end', () => {
          const text = Buffer.concat(chunks).toString();
          if (res.statusCode && res.statusCode >= 400) {
            reject(new Error(`Control API ${res.statusCode}: ${text}`));
            return;
          }
          try {
            resolve(JSON.parse(text));
          } catch {
            resolve(text);
          }
        });
        res.on('error', reject);
      });

      req.on('error', reject);
      if (body !== undefined) {
        req.end(JSON.stringify(body));
      } else {
        req.end();
      }
    });
  }

  return {
    async addDomain(domain: string): Promise<{ added: boolean }> {
      return (await request('POST', '/__ironcurtain/domains/add', { domain })) as { added: boolean };
    },
    async removeDomain(domain: string): Promise<{ removed: boolean }> {
      return (await request('POST', '/__ironcurtain/domains/remove', { domain })) as { removed: boolean };
    },
    async listDomains(): Promise<DomainListing> {
      return (await request('GET', '/__ironcurtain/domains')) as DomainListing;
    },
  };
}

// ---------------------------------------------------------------------------
// Argument validation
// ---------------------------------------------------------------------------

/** Extracts a required string argument, throwing if missing or wrong type. */
function requireStringArg(args: Record<string, unknown>, name: string): string {
  const value = args[name];
  if (typeof value !== 'string' || value.length === 0) {
    throw new Error(`Missing or invalid required argument: ${name}`);
  }
  return value;
}

// ---------------------------------------------------------------------------
// Virtual tool handler
// ---------------------------------------------------------------------------

/**
 * Dispatches a virtual proxy tool call to the control API.
 * Called by mcp-proxy-server.ts when the tool belongs to the 'proxy' server.
 */
export async function handleVirtualProxyTool(
  toolName: string,
  args: Record<string, unknown>,
  client: ControlApiClient,
): Promise<unknown> {
  switch (toolName) {
    case 'add_proxy_domain': {
      const domain = requireStringArg(args, 'domain');
      requireStringArg(args, 'justification');
      validateDomain(domain);
      const result = await client.addDomain(domain);
      if (!result.added) {
        return { status: 'already_accessible', message: 'Domain is already accessible (built-in provider)' };
      }
      return { status: 'added', domain };
    }
    case 'remove_proxy_domain': {
      const domain = requireStringArg(args, 'domain');
      const result = await client.removeDomain(domain);
      return { status: result.removed ? 'removed' : 'not_found', domain };
    }
    case 'list_proxy_domains':
      return client.listDomains();
    default:
      throw new Error(`Unknown virtual proxy tool: ${toolName}`);
  }
}
