name: Bug Report
description: Report a bug in IronCurtain
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please fill out the sections below so we can reproduce and fix the issue.

        **Security vulnerabilities:** If this is a security issue, please email security@provos.org instead of opening a public issue. See [SECURITY.md](https://github.com/provos/ironcurtain/blob/main/SECURITY.md).
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to trigger the bug.
      placeholder: |
        1. Configure MCP servers with ...
        2. Write constitution with ...
        3. Run `ironcurtain start "..."`
        4. Observe ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: IronCurtain version
      description: Output of `npx @provos/ironcurtain --version` or the git commit hash.
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: Node.js version
      description: Output of `node --version`.
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Linux
        - macOS
        - Windows (WSL2)
        - Other
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Paste any relevant error output or audit log entries. Redact credentials.
      render: text
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the system is affected?
      options:
        - Policy engine
        - Policy compilation pipeline
        - Sandbox / Code Mode
        - MCP proxy / trusted process
        - Agent / AI SDK
        - Session management
        - CLI
        - Other / unsure
